name: Build Static Qt

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.6.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtbase'

    - name: Configure Qt for Static Build
      run: |
        configure.bat -static -release -no-pch -prefix "C:/Qt/Static" -skip qtwebengine -nomake tests -nomake examples

    - name: Build Qt
      run: |
        nmake
        nmake install
